version: '3.7'
services:
  events-api:
    container_name: events-api-container
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'