version: '3.7'
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  events-api:
    depends_on:
      mysqldb:
        condition: service_healthy
    container_name: events-api-container
    build:
      context: .
      dockerfile: DockerFile
    command: sh -c "npm run execute:migration && npm run build && npm start"
    volumes:
      - '.:/app'
      - 'api:/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - KEY_JWT=$KEY_JWT
volumes: 
  db:
  api: